vpc-setting.name            = "my-vpc"
vpc-setting.cidr            = "10.0.0.0/16"
vpc-setting.private_subnets = "10.0.1.0/24,10.0.2.0/24,10.0.3.0/24"
vpc-setting.public_subnets  = "10.0.101.0/24,10.0.102.0/24,10.0.103.0/24"
vpc-setting.azs             = "us-west-2a,us-west-2b,us-west-2c"

keys.development_key_name   = "development"
keys.development_key_path   = "secure/keys/development.pem"
keys.qa_key_name            = "qa"
keys.qa_key_path            = "secure/keys/qa.pem"
keys.uat_key_name           = "uat"
keys.uat_key_path           = "secure/keys/uat.pem"
keys.production_key_name    = "production"
keys.production_key_path    = "secure/keys/production.pem"
